development:
  adapter: postgresql
  encoding: utf8
  database: user_mailer_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: user_mailer_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: user_mailer
  pool: 5
